INSERT INTO PERMISSION (ID, RESOURCE, ACTION) VALUES (1, '/security/userList.xhtml', 'ALL');
INSERT INTO PERMISSION (ID, RESOURCE, ACTION) VALUES (2, '/security/userList.xhtml', 'READ');
INSERT INTO PERMISSION (ID, RESOURCE, ACTION) VALUES (3, '/security/userList.xhtml', 'WRITE');
INSERT INTO PERMISSION (ID, RESOURCE, ACTION) VALUES (4, '/security/userList.xhtml', 'DELETE');
INSERT INTO PERMISSION (ID, RESOURCE, ACTION) VALUES (5, '/security/userEdit.xhtml', 'READ');

INSERT INTO PERMISSION (ID, RESOURCE, ACTION) VALUES (6, '/cashier/orders.xhtml', 'READ');
INSERT INTO PERMISSION (ID, RESOURCE, ACTION) VALUES (7, '/cashier/orders.xhtml', 'WRITE');
INSERT INTO PERMISSION (ID, RESOURCE, ACTION) VALUES (8, '/cashier/ordersEdit.xhtml', 'READ');

INSERT INTO PERMISSION (ID, RESOURCE, ACTION) VALUES (9, '/inventory/supplierList.xhtml', 'READ');
INSERT INTO PERMISSION (ID, RESOURCE, ACTION) VALUES (10, '/inventory/supplierList.xhtml', 'WRITE');
INSERT INTO PERMISSION (ID, RESOURCE, ACTION) VALUES (11, '/inventory/supplierList.xhtml', 'DELETE');
INSERT INTO PERMISSION (ID, RESOURCE, ACTION) VALUES (12, '/inventory/supplierList.xhtml', 'ALL');

INSERT INTO PERMISSION (ID, RESOURCE, ACTION) VALUES (13, '/sales/saleCreate.xhtml', 'READ');
INSERT INTO PERMISSION (ID, RESOURCE, ACTION) VALUES (14, '/sales/saleCreate.xhtml', 'WRITE');
INSERT INTO PERMISSION (ID, RESOURCE, ACTION) VALUES (15, '/sales/saleCreate.xhtml', 'ALL');

INSERT INTO ROLE (ID, NAME) VALUES (1, 'ADMIN');

-- clave 12345678
INSERT INTO USER_ (ID, NAME, PASSWORD) VALUES (1, 'admin', 'uVQoLxtZvlhBuamIlWRLGQ==');

INSERT INTO USER_ROLE (USER_ID, ROLE_ID) VALUES (1, 1);

INSERT INTO ROLE_PERMISSION (ROLE_ID, PERMISSION_ID) VALUES (1, 1);
INSERT INTO ROLE_PERMISSION (ROLE_ID, PERMISSION_ID) VALUES (1, 2);
INSERT INTO ROLE_PERMISSION (ROLE_ID, PERMISSION_ID) VALUES (1, 3);
INSERT INTO ROLE_PERMISSION (ROLE_ID, PERMISSION_ID) VALUES (1, 4);
INSERT INTO ROLE_PERMISSION (ROLE_ID, PERMISSION_ID) VALUES (1, 5);
INSERT INTO ROLE_PERMISSION (ROLE_ID, PERMISSION_ID) VALUES (1, 6);
INSERT INTO ROLE_PERMISSION (ROLE_ID, PERMISSION_ID) VALUES (1, 7);
INSERT INTO ROLE_PERMISSION (ROLE_ID, PERMISSION_ID) VALUES (1, 8);
INSERT INTO ROLE_PERMISSION (ROLE_ID, PERMISSION_ID) VALUES (1, 9);
INSERT INTO ROLE_PERMISSION (ROLE_ID, PERMISSION_ID) VALUES (1, 10);
INSERT INTO ROLE_PERMISSION (ROLE_ID, PERMISSION_ID) VALUES (1, 11);
INSERT INTO ROLE_PERMISSION (ROLE_ID, PERMISSION_ID) VALUES (1, 12);
INSERT INTO ROLE_PERMISSION (ROLE_ID, PERMISSION_ID) VALUES (1, 13);
INSERT INTO ROLE_PERMISSION (ROLE_ID, PERMISSION_ID) VALUES (1, 14);
INSERT INTO ROLE_PERMISSION (ROLE_ID, PERMISSION_ID) VALUES (1, 15);

COMMIT ;